name: ml-env
channels:
- conda-forge
- defaults
dependencies:
- python ==3.10.8
- ipykernel
- numpy
- matplotlib
- distributed
- jupyterlab
- jupyter-server-proxy
- pandas
- scikit-learn =1.2.2
- scipy
- pip:
        - ai.cdas
        - tensorflow-macos
        - tensorflow-metal
        - keras
